// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggoirucagfdwltaqdgpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdnb2lydWNhZ2Zkd2x0YXFkZ3B0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NDg0NzQsImV4cCI6MjA2MjEyNDQ3NH0.IIjyVXzSO0j_5KrfEWu_lTDJfJ_gaLDW96oseaW2Ta4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);